# Generated by Django 2.2.5 on 2021-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('commenttime', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('movieid', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.BigIntegerField(blank=True, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
                ('vote', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('genrename', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('actorid', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('directorid', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('minus', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('relesetime', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField()),
                ('storyline', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('vote', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.TextField(blank=True, null=True)),
                ('constellation', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('nameen', models.TextField(blank=True, null=True)),
                ('namezh', models.TextField(blank=True, null=True)),
                ('profession', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('ratingid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('movieid', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ratingtime', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('img', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('watchitems', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
