# Generated by Django 2.2.5 on 2021-03-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0002_auto_20210311_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
