# Generated by Django 2.2.5 on 2021-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0002_user_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('movieid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('similarity', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itemsimilarity',
                'managed': True,
            },
        ),
    ]
