# Generated by Django 2.2.5 on 2021-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0003_itemsimilarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsimilarity',
            name='similarity',
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='itemsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
