# Generated by Django 2.2.5 on 2021-03-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0003_auto_20210312_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='localimg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
