# Generated by Django 2.2.5 on 2021-03-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0004_person_localimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='localimg',
        ),
        migrations.AddField(
            model_name='movie',
            name='localimg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
