# Generated by Django 2.2.5 on 2021-03-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0004_auto_20210307_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsimilarity',
            old_name='itemsi',
            new_name='itemsim',
        ),
    ]
