# Generated by Django 2.2.5 on 2021-03-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0005_auto_20210307_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
