# Generated by Django 2.2.5 on 2021-03-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0005_auto_20210326_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
