# Generated by Django 2.2.5 on 2021-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0006_auto_20210308_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('userid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userpre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userpreference',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
