# Generated by Django 2.2.5 on 2021-03-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0007_remove_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
