# Generated by Django 2.2.5 on 2021-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0008_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='all_score',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
