# Generated by Django 2.2.5 on 2021-04-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0010_auto_20210331_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': True, 'verbose_name': '类型', 'verbose_name_plural': '类型管理'},
        ),
        migrations.AddField(
            model_name='movie',
            name='genreids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genrename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='类型名'),
        ),
    ]
