# Generated by Django 2.2.5 on 2021-04-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0011_auto_20210401_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genreids',
        ),
    ]
