# Generated by Django 2.2.5 on 2021-04-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0012_remove_movie_genreids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'verbose_name': '评论', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AddField(
            model_name='movie',
            name='genreids',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='genre_movie', to='MovieWeb.Genre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenttime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movieid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='电影id'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='userid',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
