# Generated by Django 2.2.5 on 2021-04-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0014_auto_20210401_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='selfnote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
