# Generated by Django 2.2.5 on 2021-04-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0016_chatrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRecord',
        ),
    ]
