# Generated by Django 2.2.5 on 2021-04-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0018_chatrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='messagetime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
