# Generated by Django 2.2.5 on 2021-04-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0019_chatrecord_messagetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRecord',
        ),
    ]
