# Generated by Django 2.2.5 on 2021-04-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0021_chatrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='type',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
