# Generated by Django 2.2.5 on 2021-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0022_chatrecord_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='commenttime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
