# Generated by Django 2.2.5 on 2021-04-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0024_auto_20210404_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrecord',
            old_name='commenttime',
            new_name='chattime',
        ),
    ]
