# Generated by Django 2.2.5 on 2021-04-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0025_auto_20210404_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatrecord',
            old_name='content',
            new_name='msg',
        ),
    ]
