# Generated by Django 2.2.5 on 2021-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0028_auto_20210407_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True, 'verbose_name': '电影', 'verbose_name_plural': '电影管理'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True, 'verbose_name': '演员', 'verbose_name_plural': '演员管理'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cover',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actorid',
            field=models.TextField(blank=True, null=True, verbose_name='演员id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True, null=True, verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='出生地'),
        ),
        migrations.AlterField(
            model_name='person',
            name='blog',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='person',
            name='constellation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='星座'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nameen',
            field=models.TextField(blank=True, null=True, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='namezh',
            field=models.TextField(blank=True, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personid',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.TextField(blank=True, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=255, null=True, verbose_name='性别'),
        ),
    ]
