# Generated by Django 2.2.5 on 2021-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0029_auto_20210408_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directorid',
            field=models.TextField(blank=True, null=True, verbose_name='导演id'),
        ),
    ]
