# Generated by Django 2.2.5 on 2021-04-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0030_auto_20210408_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='moviecover/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='personimg/'),
        ),
    ]
