# Generated by Django 2.2.5 on 2021-04-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0031_auto_20210408_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='all_score',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='总得分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='feature',
            field=models.TextField(blank=True, null=True, verbose_name='特征'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genreids',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='genre_movie', to='MovieWeb.Genre', verbose_name='类型id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='localimg',
            field=models.TextField(blank=True, null=True, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='minus',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='电影名'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='relesetime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='发行时间'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(verbose_name='平均评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='评分数'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='personimg/', verbose_name='图片文件'),
        ),
    ]
