# Generated by Django 2.2.5 on 2021-04-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0032_auto_20210409_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tag',
        ),
    ]
