# Generated by Django 2.2.5 on 2021-04-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0034_movie_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='feature',
            field=models.TextField(blank=True, default='', verbose_name='特征'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watchitems',
            field=models.TextField(blank=True, default=''),
        ),
    ]
