# Generated by Django 2.2.5 on 2021-04-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0035_auto_20210411_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='feature',
            field=models.TextField(blank=True, null=True, verbose_name='特征'),
        ),
    ]
