# Generated by Django 2.2.5 on 2021-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0037_user_focusitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='focusitems',
        ),
    ]
