# Generated by Django 2.2.5 on 2021-04-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0038_remove_user_focusitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayRating',
            fields=[
                ('ratingid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('movieid', models.BigIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ratingtime', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stayrating',
                'managed': True,
            },
        ),
    ]
