# Generated by Django 2.2.5 on 2021-04-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0039_stayrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='用户头像'),
        ),
    ]
