# Generated by Django 2.2.5 on 2021-04-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0040_comment_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectMovie',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('movieid', models.BigIntegerField(blank=True, null=True)),
                ('favoriteid', models.BigIntegerField()),
            ],
            options={
                'db_table': 'collectmovie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favoriteid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userid', models.BigIntegerField(blank=True, null=True)),
                ('favoritename', models.CharField(blank=True, max_length=255, null=True, verbose_name='收藏夹名字')),
            ],
            options={
                'db_table': 'favorite',
                'managed': True,
            },
        ),
    ]
