# Generated by Django 2.2.5 on 2021-04-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0041_collectmovie_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genreids',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='persons',
        ),
    ]
