# Generated by Django 2.2.5 on 2021-04-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0044_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
