# Generated by Django 2.2.5 on 2021-05-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0045_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stayrating',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
